image: docker.gamechanger.io/test/prerender
git:
  depth: 10
env:
  - REPO=/var/cache/drone/src/github.com/gamechanger/prerender
script:
  - cd $REPO
  - npm install
  - npm shrinkwrap
  - tests_complete prerender npm-shrinkwrap.json
notify:
  webhook:
    urls:
      - http://localhost:7777/webhook
    on_success: true
    on_failure: true
